### ISSUE TITLE
Alfred preferences plist not resolving correctly

### ISSUE THREAD

**Issue by djknight90** [importre/alfred-slack-status#2]
When I try and run this it isn't correctly finding the preferences file.

`{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/dknight/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist`

Looking into the file system my Alfred preferences is actually `com.runningwithcrayons.Alfred-3.plist`, not `com.runningwithcrayons.Alfred-Preferences-3.plist`?

I had a look in the source code but can't work out how that path is getting resolved? I assume it has something to do with https://github.com/samverschueren/resolve-alfred-prefs?

**Comment by importre** [comment]
I think it's similar to [this issue]. Would you please check the link? :)

[this issue]: https://github.com/sindresorhus/alfred-emoj/issues/8

**Comment by djknight90** [comment]
Thanks! No that wasn't actually the problem. I have Hazel installed and have it configured to be "smart" about removing apps when I delete them (it finds associated files and deletes those too.) When I deleted Alfred 2, it must have cleaned up some Alfred 3 files accidentally. Reinstalling Alfred 3 meant the config file was there, and the install was successful. Thanks again!
